# Generated by Django 5.1.6 on 2025-02-26 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('time', models.CharField(choices=[('capim_fc', 'Capim FC'), ('dendele', 'Dendele'), ('desimpedidos_goti', 'Desimpedidos Goti'), ('fluxo', 'Fluxo FC'), ('funkbol', 'Funkbol'), ('furia', 'Furia FC'), ('g3x', 'G3X'), ('loud', 'Loud SC'), ('nyvelados', 'Nyvelados'), ('real_elite', 'Real Elite')], max_length=50)),
                ('posicao', models.CharField(choices=[('GK', 'Goleiro'), ('MEI', 'Meio-Campo'), ('ATA', 'Atacante'), ('DEF', 'Defensor')], max_length=50)),
                ('defesa', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('passe', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('habilidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('chute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('duelo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('fisico', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='card/')),
            ],
        ),
    ]
