# Generated by Django 5.1.6 on 2025-02-26 02:49

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcreate',
            old_name='name',
            new_name='fist_name',
        ),
        migrations.AddField(
            model_name='cardcreate',
            name='last_name',
            field=models.CharField(default='desconhecido', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models.path_and_rename),
        ),
    ]
