# Generated by Django 5.1.6 on 2025-02-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_name_cardcreate_fist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcreate',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
