# Generated by Django 5.1.6 on 2025-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_fist_name_cardcreate_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcreate',
            name='over_all',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
