# Generated by Django 5.1.6 on 2025-02-26 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardcreate_over_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcreate',
            name='chute',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='defesa',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='duelo',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='fisico',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='habilidade',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='over_all',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='passe',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='posicao',
            field=models.CharField(choices=[('GK', 'Goleiro'), ('MEI', 'Meio-Campo'), ('ATA', 'Atacante'), ('DEF', 'Defensor')], default=('GK', 'Goleiro'), max_length=50),
        ),
        migrations.AlterField(
            model_name='cardcreate',
            name='time',
            field=models.CharField(choices=[('capim_fc', 'Capim FC'), ('dendele', 'Dendele'), ('desimpedidos_goti', 'Desimpedidos Goti'), ('fluxo', 'Fluxo FC'), ('funkbol', 'Funkbol'), ('furia', 'Furia FC'), ('g3x', 'G3X'), ('loud', 'Loud SC'), ('nyvelados', 'Nyvelados'), ('real_elite', 'Real Elite')], default=('capim_fc', 'Capim FC'), max_length=50),
        ),
    ]
