# Generated by Django 5.1.6 on 2025-02-27 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardcreate_chute_alter_cardcreate_defesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcreate',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='card/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
