# Generated by Django 5.1.6 on 2025-03-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_cardcreate_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcreate',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='card/'),
        ),
    ]
